---
- name: Install tomcat on web
  hosts: web
  become: yes

  tasks:
    - name: "Ensure tomcat installed"
      apt:
        pkg:
        - tomcat9
        state: installed

- name: "Setup java application for homework lesson8"
  hosts: mvn
  become: yes

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
      update_cache: yes
    - name: "Ensure that jdk, maven and git are installed"
      apt:
        pkg:
        - default-jdk
        - git
        - maven
        state: installed
    - name: "Clone jdk app from github"
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /tmp/boxfuse-sample-java-war-hello/
        update: yes
        clone: yes
    - name: "build java app"
      command: cd /tmp/boxfuse-sample-java-war-hello; mvn package
    - name: "copy war file to webserver "
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/*.war
        dest: /var/lib/tomcat9/webapps/
        mode: pull
        delegate_to: web
  


    

